[package]
name = "cvxrs"
version = "0.1.0"
authors = ["Vinícius Dantas <viniciusdantas@bct.ect.ufrn.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
osqp = "0.6.0"
approx = "0.3.2"
